const persons = {
    1: {
        "name": "MAGALLANES",
        "cpuName": "AMD Athlon II X2 250",
        "realPerformanceMono": 142,
        "realPerformanceMulti": 274,
        "teoricalPerformanceMulti": 283,
        "gpuName": "AMD R5 340X (OC)",
        "vram": 2,
        "gpuPerformance": 1235,
        "gpuDXSupport": 11.1,
        "gpuOpenGLSupport": 4.6,
        "osName": "Windows",
        "osVersion": "10 Enterprise LTSC",
        "ramSize": 2,
        "ramspeed": 800,
        "ramDDRAndType": 21,
        "motherBoardname": "ECS EliteGroups",
        "addedDate": 13012026
    },
    2: {
        "name": "Salva",
        "cpuName": "Intel Core i5 4760S",
        "realPerformanceMono": 405,
        "realPerformanceMulti": 1510,
        "teoricalPerformanceMulti": 1600,
        "gpuName": "GTX 750Ti EVGA SuperClocked",
        "vram": 2, // Dedicada
        "gpuPerformance": 3902,
        "gpuDXSupport": 11.0,
        "gpuOpenGLSupport": 4.6,
        "osName": "Windows",
        "osVersion": "10 Enterprise LTSC",
        "ramSize": 16,
        "ramspeed": 1600,
        "ramDDRAndType": 31,
        "motherBoardname": "Esonic H81DA1",
        "addedDate": 13012026
    },
    3: {
        "name": "Rubín",
        "cpuName": "Intel Core 2 Duo T5750",
        "realPerformanceMono": 161,
        "realPerformanceMulti": 316,
        "teoricalPerformanceMulti": 320,
        "gpuName": "Intel GMA X3100 (965)",
        "vram": 0.25, // Compartida (Dinámica)
        "gpuPerformance": 109,
        "gpuDXSupport": 9.3,
        "gpuOpenGLSupport": 2.0,
        "osName": "Windows",
        "osVersion": "10 LTSB",
        "ramSize": 3,
        "ramspeed": 666,
        "ramDDRAndType": 23,
        "motherBoardname": "VAIO",
        "addedDate": 15012026
    },
    4: {
        "name": "Diego",
        "cpuName": "Ryzen 5 5600G",
        "realPerformanceMono": 606,
        "realPerformanceMulti": 4536,
        "teoricalPerformanceMulti": 6500,
        "gpuName": "AMD Radeon Graphics (Cezanne)",
        "vram": 2, // Compartida (Asignable hasta 2GB usualmente)
        "gpuPerformance": 2547,
        "gpuDXSupport": 12.0,
        "gpuOpenGLSupport": 4.6,
        "osName": "Windows",
        "osVersion": "10",
        "ramSize": 8,
        "ramspeed": 3200,
        "ramDDRAndType": 41,
        "motherBoardname": "None",
        "addedDate": 16012026
    },
    5: {
        "name": "Eduardo",
        "cpuName": "AMD Athlon II X2 245",
        "realPerformanceMono": 157,
        "realPerformanceMulti": 286,
        "teoricalPerformanceMulti": 265,
        "gpuName": "AMD R5 340X",
        "vram": 2, // Dedicada
        "gpuPerformance": 1235,
        "gpuDXSupport": 11.1,
        "gpuOpenGLSupport": 4.6,
        "osName": "Windows",
        "osVersion": "10 LTSC",
        "ramSize": 4,
        "ramspeed": 1333,
        "ramDDRAndType": 33,
        "motherBoardname": "MSI",
        "addedDate": 15012026
    },
    6: {
        "name": "Julio",
        "cpuName": "Intel Core i7 2600S",
        "realPerformanceMono": 256,
        "realPerformanceMulti": 1285,
        "teoricalPerformanceMulti": 2100,
        "gpuName": "Intel HD Graphics 2000",
        "vram": 0.5, // Compartida
        "gpuPerformance": 250,
        "gpuDXSupport": 10.1,
        "gpuOpenGLSupport": 4.5,
        "osName": "Windows",
        "osVersion": "7 Ultimate (Lite)",
        "ramSize": 16,
        "ramspeed": 1333,
        "ramDDRAndType": 33,
        "motherBoardname": "Jimed",
        "addedDate": 16012026
    },
    7: {
        "name": "Johnalbert",
        "cpuName": "Intel Core i3 14100",
        "realPerformanceMono": 720,
        "realPerformanceMulti": 3610,
        "teoricalPerformanceMulti": 15500,
        "gpuName": "Intel UHD Graphics 730",
        "vram": 1, // Compartida
        "gpuPerformance": 1539,
        "gpuDXSupport": 12.00,
        "gpuOpenGLSupport": 4.6,
        "osName": "Windows",
        "osVersion": "10 Pro",
        "ramSize": 8,
        "ramspeed": 4800,
        "ramDDRAndType": 33,
        "motherBoardname": "Jimed",
        "addedDate": 16012026
    },
    8: {
        "name": "Eduard",
        "cpuName": "AMD Ryzen 5 2400G",
        "realPerformanceMono": 452,
        "realPerformanceMulti": 2401,
        "teoricalPerformanceMulti": 8730,
        "gpuName": "AMD Radeon RX Vega 11",
        "vram": 2, // Compartida
        "gpuPerformance": 2091,
        "gpuDXSupport": 12.0,
        "gpuOpenGLSupport": 4.6,
        "osName": "Windows",
        "osVersion": "11 Pro",
        "ramSize": 10,
        "ramspeed": 3200,
        "ramDDRAndType": 41,
        "motherBoardname": "NONE",
        "addedDate": 16012026
    }
};
